<?xml version="1.0" encoding="utf-8"?><Database Name="SandBox" Class="ParachuteModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SandBox;Integrated Security=True" SettingsObjectName="Parachute.Properties.Settings" SettingsPropertyName="SandBoxConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[__ParachuteAppliedScriptsLogs]" Member="ParachuteAppliedScriptsLogs">
    <Type Name="ParachuteAppliedScriptsLog">
      <Column Name="ParachuteAppliedScriptsLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScriptName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="SchemaVersion" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[__ParachuteSchemaChangeLogs]" Member="ParachuteSchemaChangeLogs">
    <Type Name="ParachuteSchemaChangeLog">
      <Column Name="ParachuteSchemaChangeLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MajorReleaseNumber" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MinorReleaseNumber" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PointReleaseNumber" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="ScriptName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>