IF EXISTS (
	SELECT	* 
	FROM	INFORMATION_SCHEMA.TABLES 
	WHERE	TABLE_NAME = '__ParachuteAppliedScriptsLogs'
	AND		TABLE_SCHEMA = 'dbo'
) AND EXISTS (
	SELECT	* 
	FROM	INFORMATION_SCHEMA.TABLES 
	WHERE	TABLE_NAME = '__ParachuteSchemaChangeLogs'
	AND		TABLE_SCHEMA = 'dbo'
) AND EXISTS (
	SELECT	* 
	FROM	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
	WHERE	CONSTRAINT_NAME = 'FK___ParachuteAppliedScriptsLogs___ParachuteSchemaChangeLogs'
	AND		CONSTRAINT_SCHEMA = 'dbo'
)
BEGIN
	SELECT 1
END
ELSE 
BEGIN
	SELECT 0
END
